version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          post-steps:
            - store_test_results:
                path: ./reports/junit
            - store_artifacts:
                path: cypress/videos
            - store_artifacts:
                path: cypress/screenshots
            - run:
                name: Parse Test Results
                command: node ./scripts/parseJunit.js $CIRCLE_PR_USERNAME $CIRCLE_BRANCH
                when: always
